loglevel: info
cpus: 1
monitoring:
  port: 5555
protocols:
  http:
    enable: true
    mocks_dir: './mocks'
    port: 3007
backup:
  enable: false
cache:
  enable: false
  ttl_seconds: 300
injection:
  enable: true
origins:
  - http://localhost:8007
  - http://127.0.0.1:8007
validation:
  enable: false
